import type { Metadata } from "next";
import "./globals.css";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head className="m-0 p-0">
        <link href="/dist/output.css" rel="stlylesheet" />
      </head>
      <body className="m-0 p-0">{children}</body>
    </html>
  );
}
